const helpData = {
    skills: "<h3>1-Klick Würfeln</h3><p>Du kannst jederzeit direkt auf deine <b>Basiswerte</b> (Handeln, Wissen, Soziales) oder auf einzelne <b>Skills</b> klicken, um eine automatische Probe auf diesen Wert abzulegen!</p><p>Bei <b>Skills</b> werden kritische Erfolge (die unteren 10%) und Patzer (die oberen 10%) automatisch anhand deines aktuellen Wertes mitberechnet. Auf <b>Basiswerte</b> sind laut Regelwerk keine kritischen Erfolge möglich, Patzer können hier aber weiterhin auftreten.</p>",
    
    logs: "<h3>Drag & Drop Notizen</h3><p>Du kannst jeden Eintrag aus deinem <b>Aktions-Logbuch</b> oder den <b>Letzten Würfen</b> einfach mit der Maus greifen (klicken & gedrückt halten) und direkt rüber in dein <b>Notizfeld</b> ziehen!</p><p>So kannst du besondere Ereignisse oder knappe Würfe blitzschnell dokumentieren und musst sie nicht abtippen.</p>",
    
    gbp: "<h3>Geistesblitzpunkte (GBP)</h3><p>Geistesblitze sind seltene Meta-Punkte, die dir der Spielleiter für besonders kreatives Spielen oder gute Ideen geben kann. Du kannst sie jederzeit ausgeben, um die Story zu deinen Gunsten zu verändern (z.B. einen verpatzten Wurf doch noch zu schaffen oder einen versteckten Hinweis zu bekommen).</p>",
    
    inventory: "<h3>Sortieren & Löschen</h3><p>Du kannst deine Items und Waffen ganz einfach per <b>Drag & Drop</b> sortieren! Klicke auf das kleine Anfasser-Symbol (<i class='fa-solid fa-bars'></i>) auf der linken Seite eines Items, halte die Maus gedrückt und ziehe es an die gewünschte Position.</p>",
    
    dice: "<h3>Bonus & Custom Würfel</h3><p><b>Bonus/Malus:</b> Hat dir der Spielleiter einen situativen Bonus (z.B. +10) oder Malus (z.B. -15) gegeben? Trage ihn hier ein! Der Wert wird automatisch in deinen <i>nächsten</i> Skill-Wurf eingerechnet und danach direkt wieder zurückgesetzt.</p><p><b>Custom:</b> Hier kannst du unübliche Würfelkombinationen werfen, z.B. <code>3w8</code> für drei achtseitige Würfel.</p>",
    
    status: "<h3>Status-Effekte</h3><p>Hier kannst du dir temporäre Effekte wie <i>Krankheit</i>, <i>Vergiftet</i> oder <i>Rausch</i> notieren. Du kannst ihnen einen Wert geben (z.B. <i>1W6</i> oder <i>-10</i>) und sie farblich markieren (Rot = Malus, Grün = Bonus).</p><p>Klicke auf einen bestehenden Status-Tag, um ihn wieder zu löschen.</p>",
    
    gmSync: "<h3>Theme Sync</h3><p>Wenn du den Haken bei <b>Sync to Players</b> setzt, wird das von dir hier ausgewählte Vibe-Theme <b>automatisch auf alle Bildschirme deiner Spieler erzwungen</b>.</p><p>Das ist ein tolles Werkzeug, um in besonderen Momenten (z.B. bei einem Szenenwechsel in die Unterwelt) die Stimmung am virtuellen Tisch für alle gleichzeitig zu lenken!</p>",

    gmLayout: "<h3>Panels umsortieren</h3><p>Jedes Panel in der Hauptspalte (Spielerkarten, Zufallsgenerator, NSC-Liste, Quest-Logbuch, Schiff, Seekampf, Tischmitte, SL-Notizen) hat oben einen kleinen Ziehgriff <i class='fa-solid fa-grip-lines'></i>. Daran gepackt, kannst du das Panel per Drag &amp; Drop an eine beliebige Position ziehen - egal ob gerade Hausregeln aktiv sind oder nicht.</p><p>Die Reihenfolge bleibt in diesem Browser gespeichert, auch über einen Reload hinweg. Über <b>Reihenfolge zurücksetzen</b> geht's zurück zur Standard-Anordnung.</p>",
    
    gmNotes: "<h3>Notizen-Archiv & Save/Load</h3><p>Das Dashboard speichert zu jedem verbundenen Charakter automatisch ein eigenes, für die Spieler geheimes Notizfeld in deinem Browser.</p><p>Klicke auf <b>Notizen-Archiv</b>, um auch die Notizen von Spielern einzusehen, die gerade offline sind.</p><p>Da die Notizen lokal im Browser liegen, solltest du sie nach jeder Session mit <b>Save</b> als Backup herunterladen und vor der nächsten Session mit <b>Load</b> wiederherstellen!</p>",
    
    multiplayer: "<h3>Live-Sync & Discord</h3><p><b><i class='fa-solid fa-satellite-dish'></i> Live-Sync (Multiplayer):</b> Dies ist das GM-Dashboard Feature! Ein Spieler oder der Spielleiter klickt auf diesen Button, um einen Server-Code zu generieren. Die anderen Spieler geben diesen Code ein und verbinden sich live (Peer-to-Peer, ohne echten Server). Der Host sieht alle Spieler-Bögen, HP und Würfe in Echtzeit!</p><p><b><i class='fa-brands fa-discord'></i> Discord Sync:</b> Du kannst hier eine Discord-Webhook-URL eintragen. Dann werden alle deine Würfe (und auf Wunsch auch HP-Verluste) vollautomatisch direkt in euren Discord-Kanal gepostet, sodass alle sie lesen können.</p>",
    
    gmDice: "<h3>GM Würfel-Box</h3><p><b>Schnelle Würfe:</b> Als Spielleiter hast du hier direkten Zugriff auf die wichtigsten Würfel (1W100 für allgemeine Proben, 1W6 für einfachen Schaden).</p><p><b>Custom Würfel:</b> Brauchst du etwas Spezielles (z.B. für Monster-Schaden oder Zufallstabellen)? Gib einfach dein gewünschtes Format ein, z.B. <code>2w8</code> oder <code>1w20+5</code>.</p><p><i>Hinweis: Deine Würfe tauchen sofort live im Feed auf und lösen bei Krits (1-10) oder Patzern (91-100) beim W100 auch bei dir die passenden visuellen Effekte aus!</i></p>"
,

    customSound: "<h3>🔒 Eigener privater Sound</h3><p>Hast du einen Song oder Sound, den du <b>nicht öffentlich verwenden darfst</b> (z.B. nur für den privaten Rahmen lizenziert), aber trotzdem in eurer Runde nutzen willst? Lade ihn hier hoch!</p><p>Die Datei wird <b>ausschließlich lokal in deinem Browser</b> gespeichert (nie im Repository, nie auf der öffentlich gehosteten Seite). Beim Klick auf \"Für alle abspielen\" wird sie direkt per WebRTC an die aktuell verbundenen Spieler übertragen, genau wie eure Würfe und HP-Updates auch - es findet keine Veröffentlichung auf irgendeiner Plattform statt.</p><p><i>Hinweis: Die Datei bleibt auf diesem Gerät gespeichert, bis du sie über den Papierkorb-Button wieder entfernst. Bei einem Wechsel des Browsers/Geräts musst du sie erneut hochladen.</i></p>"
,

    hausregeln: "<h3>Hausregeln & Regelpakete</h3>" +
                "<p>Viele Runden spielen HTBAH mit eigenen Erweiterungen. Ein <b>Regelpaket</b> bündelt so eine Erweiterung: eine feste Talentliste, abweichende Punktekosten, einen Talentbaum, Wesen-Boni und Würfeltabellen.</p>" +
                "<p><b>Ohne Paket</b> rechnet der Bogen exakt nach dem offiziellen Regelwerk - es ändert sich nichts.</p>" +
                "<p><b>Für den Spielleiter:</b> Wähle das Paket eurer Runde, klicke auf <i>Übernehmen</i> und dann auf <i>An Spieler senden</i>. Alle verbundenen Spieler bekommen die Einstellung sofort, neue Spieler automatisch beim Beitreten.</p>" +
                "<p><b>Für Spieler:</b> Du musst nichts tun - wenn dein Spielleiter ein Paket verteilt, wird es bei dir übernommen. Du kannst es auch selbst wählen, wenn ihr ohne Live-Sync spielt.</p>" +
                "<p><i>Eigenes Paket? Das Format ist in DATA_FORMAT.md im Repository beschrieben - ein JSON reicht, es lässt sich über \"Aus Datei\" laden und wird beim Verteilen mit an die Spieler geschickt.</i></p>",

    randomizer: "<h3>Zufallsgenerator</h3>" +
                "<p>Ein reines Prep-Werkzeug für dich als Spielleiter - nichts davon geht automatisch an die Spieler. Drei Tabellen-Pakete stehen bereit: <b>Allgemein</b> (setting-neutral), <b>Piraten</b> (generisches Flair) und <b>Eldara</b> (kanonisch, passend zum Regelpaket „eldora-arrrrr\").</p>" +
                "<p><b>NSC würfeln</b> baut in einem Rutsch einen Charakter: Name, Trefferort/Rolle, Haltung, Auffälligkeit, Motivation - optional inklusive Wesen/Monster mit einer passenden „Besonderen Eigenschaft\" aus dem Eldara-Regelwerk (rein als Flavor-Text, noch nicht an die Talentbaum-Punkte gekoppelt). Ort, Namensstil, Geschlecht, Grundhaltung und Wesen lassen sich einzeln festlegen, wenn du einen bestimmten Charakter brauchst - auf \"Zufällig\" bleibt es eine Überraschung.</p>" +
                "<p><b>Magischer Gegenstand</b> würfelt aus den 44 Eldara-Artefakten und kann per Knopf direkt <b>versteckt in die Tischmitte</b> gelegt werden - du musst nichts abtippen, nur später aufdecken.</p>" +
                "<p>Ein gewürfelter NSC lässt sich per Knopf direkt <b>in die NSC-Liste übernehmen</b> - dein dauerhaftes Gedächtnis für NPCs der Runde, siehe dazu die eigene Hilfe zur NSC-Liste.</p>" +
                "<p>Unter <b>Tabellen durchstöbern</b> findest du alle Einzeltabellen nach Paket und Kategorie sortiert - u.a. die reguläre Eldara-Waffen-Preisliste (\"Waffen des Dunklen Meeres\", S.32) und herstellbare Gegenstände (Gifte, Bomben, Technik-Gadgets, S.29f.). Jedes Ergebnis lässt sich neu würfeln oder per Klick in die <b>SL-Notizen</b> übernehmen - Ergebnisse aus den Kategorien <b>Gegenstände</b> und <b>Waffen</b> zusätzlich direkt <b>in die Tischmitte legen</b> (Waffen landen dort korrekt mit Schaden-Feld statt als Text-Beschreibung).</p>",

    gmEingriff: "<h3>🪄 SL-Eingriff</h3>" +
                "<p>Über den <i>Eingriff</i>-Knopf in der Spielerkarte greifst du direkt in den Bogen eines Spielers ein: <b>Gegenstand, Waffe oder Geld geben</b> (negativer Betrag zieht Geld ab) und <b>Status-Effekte setzen oder entfernen</b>.</p>" +
                "<p>Hat der Spieler ein <b>Wesen/Monster</b> gewählt (Eldara-Talentbaum), kannst du hier auch <b>Monsterpunkte</b> vergeben - die treiben Rang und Skillpunkte seines Wesen-Asts, statt aus eigenen Talentpunkten zu kommen.</p>" +
                "<p>Bei aktivem Eldara-Paket kannst du hier außerdem eine <b>Sonderfreigabe: Talentbaum</b> erteilen - einer der 19 NSC-/Monster-Bäume (Werwolf, Vampir, …) wird dann für genau diesen Spieler als zusätzliche Wesen-Option wählbar (Ausnahmefall laut Regelwerk „kontaktiert bitte den Spielleiter"). Ein Klick auf ✕ nimmt die Freigabe wieder zurück.</p>" +
                "<p><b>Verdeckt:</b> Mit dem Haken erscheint beim Spieler weder ein Logbuch-Eintrag noch ein Hinweis - der Wert ist einfach da. Gedacht für Flüche, heimlich zugesteckte Gegenstände oder eine schleichende Vergiftung, die nicht mit Fanfare ankommen sollen. Ohne Haken landet der Eingriff wie jede andere Änderung im Aktions-Logbuch des Spielers, mit dem Zusatz „vom Spielleiter\".</p>" +
                "<p><i>In deinem Live-Feed steht jeder Eingriff - auch die verdeckten, damit du nachvollziehen kannst, was du wann getan hast.</i></p>",

    gruppe: "<h3>Gruppe</h3>" +
            "<p>Sobald du im Live-Sync mit deinem Spielleiter verbunden bist, siehst du hier deine <b>Mitspieler</b>: Bild, Name, Lebenspunkte und ihre aktuellen Status-Effekte. Fällt jemand auf 10 LP oder weniger, blinkt die Zeile rot.</p>" +
            "<p>Mehr ist es absichtlich nicht - Skills, Inventar und Notizen der anderen bleiben privat bzw. Sache des Spielleiters. Die Farbe kommt vom Spielleiter-Dashboard.</p>",

    teamwuerfel: "<h3>Team-Würfel</h3>" +
                 "<p>Sobald du im Live-Sync verbunden bist, siehst du hier die <b>Würfe deiner ganzen Gruppe</b> in Echtzeit - deine eigenen eingeschlossen. Kein Discord-Webhook mehr nötig, um mitzuverfolgen, was am Tisch gewürfelt wird.</p>" +
                 "<p>Es laufen nur echte Würfe rein (Würfel-Tool, Skill- und Attributproben) - allgemeine Logbuch-Einträge wie Items oder HP-Änderungen tauchen hier nicht auf, das würde nur unnötig Rauschen. Die Farbe je Spieler entspricht der im Spielleiter-Dashboard.</p>" +
                 "<p><i>Reiner Live-Feed - nichts davon wird gespeichert. Wer neu beitritt, sieht nur Würfe ab dem eigenen Beitritt.</i></p>",

    tischmitte: "<h3>Tischmitte</h3>" +
                "<p>Die Tischmitte ist eine geteilte Ablage zwischen Spielleiter und Spielern - wie Beute, die in der Mitte des Tisches liegt.</p>" +
                "<p><b>Für den Spielleiter:</b> Lege Gegenstände, Waffen oder Geld ab. <b>Versteckte</b> Einträge siehst nur du - so kannst du den Loot eines Abenteuers schon vor der Session vorbereiten. Findet die Gruppe die Truhe, klickst du auf <i>Aufdecken</i> (oder <i>Alle aufdecken</i>) und die Beute erscheint bei allen Spielern. Über <i>Geben an …</i> schiebst du etwas auch direkt einem bestimmten Charakter ins Inventar.</p>" +
                "<p><b>Für Spieler:</b> Sobald der Spielleiter etwas aufdeckt, klappt die Tischmitte bei dir auf. Mit <i>Nehmen</i> wandert der Gegenstand in dein Inventar (Waffen zu den Waffen, Geld in die Kasse). Greifen zwei gleichzeitig zu, bekommt nur einer den Gegenstand - der Spielleiter entscheidet. Über <i>Eigenes ablegen</i> kannst du auch etwas aus deinem Inventar in die Mitte legen, z.B. um es einem Mitspieler zu geben - bei Stapeln (3x Verbandskasten) wählst du, wie viele davon.</p>" +
                "<p><i>Die Tischmitte des Spielleiters bleibt in seinem Browser gespeichert, bis er sie leert - auch über einen Reload hinweg.</i></p>",

    inventarraster: "<h3>Rasterinventar</h3>" +
                     "<p>Bildet das Eldara-Regelwerk ab (Kapitel \"Inventar &amp; Rucksack\", S.25f.): statt einer endlosen Liste hast du feste Trageflächen - <b>Gürtel</b> (6 Plätze), <b>Gürtelbeutel</b> (2) und <b>Rucksack</b> (12, weniger bei schwererer Rüstung). Jeder Gegenstand belegt laut Größentabelle 1, 2 oder 3 Felder - die Größe stellst du direkt an der Karte ein.</p>" +
                     "<p><b>Rüstung</b> (S.27f.): sechs echte Ausrüstungs-Plätze - Helm, 2x Schulter, Brust, 2x Bein - jeweils wahlweise mit Leder/Kette/Platte bestückbar, jede Kombination mit eigenem Rüstungswert und Gold-Preis. Die Summe aller getragenen Werte ergibt deine Stufe (Ungepanzert 0 / Leicht 1-10 / Mittel 11-20 / Schwer 21+), die wie bisher den Rucksack verkleinert: -1 Platz bei Mittel, -2 bei Schwer. <i>Das Regelwerk nennt laut S.27 noch zusätzliche Mali auf Bewegung/Handeln/Heimlichkeit je Stufe - diese Werte sind in der Quelle nicht eindeutig lesbar und daher hier (noch) nicht automatisiert; im Zweifel selbst im Regelbuch nachschlagen.</i></p>" +
                     "<p><b>Zusatztaschen</b> (bis zu 3 gleichzeitig) geben zusätzliche Plätze - klein +3, groß +5 - kosten dich aber -3 bzw. -5 auf Handeln, solange du sie trägst. Das musst du selbst beim Würfeln im Bonus/Malus-Feld gegenrechnen, das Tool zieht es nicht automatisch ab.</p>" +
                     "<p>Zum Umsortieren einen Gegenstand auf ein anderes Feld ziehen. Ist dort schon ein 1-Feld-Gegenstand, tauschen beide automatisch die Plätze.</p>" +
                     "<p><b>Waffen ziehen mit um:</b> Sobald Eldara aktiv ist, verschwindet das klassische Waffen-Panel - deine Waffen landen automatisch als eigene Karten im Raster (Standardgröße 2 Felder, änderbar), inklusive Schaden-Feld und Würfel-Knopf. Passt eine Waffe mangels Platz nicht rein, bleibt sie vorerst im alten Bestand und du bekommst eine Warnung. Schaltest du Eldara wieder aus, wandern alle Waffen automatisch zurück ins klassische Panel.</p>" +
                     "<p><i>Vereinfacht gegenüber dem Regelwerk: 0,5-Gegenstände (Dolche, Tränke) belegen hier volle 1 Feld statt sich zu zweit einen Platz zu teilen, und die \"2 Waffen\"-Sonderplätze am Gürtel/Rucksack sind nicht als eigene, waffen-exklusive Zone abgebildet - eine Waffe belegt einfach ihre normalen 1-3 Felder wie jeder andere Gegenstand.</i></p>" +
                     "<p>Diese Ansicht ersetzt die normale Inventarliste nur, solange das Regelpaket \"eldora-arrrrr\" aktiv ist - ohne Hausregel bleibt alles wie gewohnt unbegrenzt.</p>",

    schiff: "<h3>Schiffs-Inventar</h3>" +
            "<p>Eldara-Hausregel: das Schiff als gemeinsame Heimat der Crew. Anders als die Tischmitte ist alles hier <b>immer für alle sichtbar</b> - kein Verstecken, das ist ja euer eigener Besitz.</p>" +
            "<p><b>Lager:</b> Jede Schiffsklasse hat laut Regelwerk (S.32) eine feste Kapazität - Kanonenboot 20, Schoner 50, Brigg 100, Fregatte 150, Kriegsschiff 250. Der SL wählt die Klasse; ist das Lager voll, lässt sich nichts Neues mehr ablegen.</p>" +
            "<p><b>Mitnahme-Grenze:</b> \"Nehmen\" klappt nur, wenn im eigenen <a href=\"#\" onclick=\"event.preventDefault(); showHelp('inventarraster')\">Rasterinventar</a> noch ein passendes Feld frei ist. Ist nichts frei, bekommst du eine klare Rückmeldung statt einer stillen Ablehnung.</p>" +
            "<p>Über \"Eigenes aufs Schiff legen\" gibst du umgekehrt etwas aus deinem Rasterinventar an die ganze Crew ab - ist das Lager gerade voll, bekommst du es automatisch zurück statt es zu verlieren.</p>" +
            "<p><i>Das Regelwerk sagt nicht genau, wie viele Lager-Einheiten ein Gegenstand welcher Rasterinventar-Größe verbraucht - hier wird vereinfachend dieselbe Größentabelle für beides verwendet. Wirkt das Lager zu klein, einfach eine größere Schiffsklasse wählen.</i></p>" +
            "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist.</i></p>",

    seekampf: "<h3>Seekampf</h3>" +
              "<p>Taktischer Kampf-Tracker für das Regelwerk-Kapitel \"Seekampf\" (S.3-5). Die Karte kommt aus demselben Modul wie andere Kampfkarten-Tools: Rasterfelder à 200m, frei verschiebbare Schiffs-Token per Drag &amp; Drop, Zoom per Mausrad, optional ein eigenes Kartenbild (\"Karte laden\").</p>" +
              "<p><b>Deine Spieler sehen live mit:</b> Sobald du ein Schiff bewegst, würfelst oder einen Effekt einträgst, aktualisiert sich die Karte bei allen verbundenen Spielern automatisch (kurz gesammelt, nicht bei jedem einzelnen Pixel). Über \"Steuerbar von\" an einem Schiff wählst du per Klick auf Namens-Chips aus, welche Spieler es selbst auf ihrer eigenen Karte ziehen dürfen - <b>auch mehrere gleichzeitig</b>, praktisch wenn sich die ganze Crew ein Schiff teilt. Ein Zug erscheint bei dir zunächst nur als gestrichelter <b>Vorschlag</b> unter \"Offene Zugvorschläge\"; erst wenn du \"Bestätigen\" klickst, bewegt sich das Schiff wirklich (oder \"Verwerfen\", falls nicht). Nicht zugewiesene Schiffe (z.B. alle Gegner) bewegst weiterhin nur du.</p>" +
              "<p><b>Automatisiert</b> (reine Würfelmechanik ohne Charakterwerte): Initiative (1W10 je Schiff), Wind (1W8 Richtung, wechselt alle 1W6 Runden), Bewegung (Geschwindigkeits-Würfel des Schiffs + Windbonus), Kanonenfeuer-Trefferquote (W100 nach erfolgreicher Probe), kritische Trefferzonen (1W4) und der Rammschaden von \"Ramme voraus\".</p>" +
              "<p><b>Nicht automatisiert:</b> Die Manöver-Proben selbst (Steuern/Schießen/Entern/Heimlichkeit) - der Tracker kennt keine Charakterwerte, die liegen auf den einzelnen Bögen. Die Manöver-Liste unten erscheint deshalb als Nachschlage-Karte mit Malus und Effekttext; die Probe würfelt der steuernde/schießende Spieler ganz normal auf seinem Bogen (Malus manuell im Bonus/Malus-Feld eintragen). War die Probe erfolgreich, trägst du den Effekt über \"Erfolg → Effekt\" als Erinnerungs-Badge auf dem Schiff ein - prozentuale Effekte wie \"+10% Trefferchance\" fließen NICHT automatisch in die Kanonenfeuer-Trefferquote ein, du rechnest sie beim Würfeln selbst dazu (genau wie der Zusatztaschen-Malus im Rasterinventar).</p>" +
              "<p><b>Strukturpunkte:</b> Sinkt ein Schiff auf 0, markiert es der Tracker als sinkend. Kritische Trefferzonen wie \"Segel zerstört\" oder \"Mastbruch\" setzen einen dauerhaften Schadens-Badge (× zum Entfernen, sobald repariert) - er halbiert automatisch das Ergebnis beim nächsten Bewegungswurf.</p>" +
              "<p><b>Riffe, Inseln, Kanonenreichweiten & Co.:</b> Mit dem Werkzeug \"Zeichnen\" malst du Freihand-Linien, Linien, Kreise oder Rechtecke direkt auf die Karte (Form und Farbe daneben einstellbar) - praktisch für Untiefen, Nebelbänke oder \"bis hierhin reicht die Breitseite\". \"Formen löschen\" räumt alle Zeichnungen weg, \"Rückgängig\" nimmt die letzte zurück. Für benannte Orte gibt es zusätzlich <b>Kartenmarkierungen</b> (Riff/Insel/Wrack/Sonstiges, mit passendem Symbol) als eigene kleine Token, die wie Schiffe frei verschiebbar sind, aber nicht in der Einheiten-Liste oder der Initiative auftauchen. Über die − / + an jedem Marker-Chip lässt sich seine Größe auf der Karte anpassen (große Insel vs. kleine Insel, großes Riff vs. kleines Riff, ...). Beides - Zeichnungen wie Marker - übersteht ein \"Gefecht zurücksetzen\", nur die Kampfteilnehmer selbst werden dabei entfernt.</p>" +
              "<p><b>Eigenes Kartenbild einpassen:</b> Lädst du eine eigene Seekarte hoch, passt das Standard-Raster selten auf Anhieb. Über \"Raster\"/\"Einrasten\" schaltest du Linien bzw. das Einrasten auf halbe Felder an/aus, die Farbpunkte wählen eine zum Bild passende Rasterfarbe, und \"Feldgröße\"/\"Versatz X\"/\"Versatz Y\" (in Pixeln) schieben und stauchen das Raster, bis es zu den Feldern auf deinem Bild passt. All das wird - wie Schiffe und Marker - automatisch an deine Spieler übertragen, sie sehen also dieselbe Karte.</p>" +
              "<p><i>Vereinfacht: die Zeile mit den zusätzlichen Bewegungs-/Handeln-/Heimlichkeit-Mali je Rüstungsstufe (S.27) ist im Quelltext nicht eindeutig lesbar und daher nirgends im Tool verrechnet.</i></p>" +
              "<p><i>Nur sichtbar, solange das Regelpaket \"eldora-arrrrr\" aktiv ist. Dein Gefechtsstand bleibt wie bei Tischmitte/Schiff in deinem Browser gespeichert, auch über einen Reload hinweg.</i></p>",

    quests: "<h3>Quest-Logbuch</h3>" +
            "<p><b>Für den Spielleiter:</b> Lege Quests mit Name, Beschreibung und optional einer Verknüpfung zu einem NSC aus deiner NSC-Liste an. Jede neue Quest ist erst <b>versteckt</b> - nur du siehst sie. Über das Augen-Symbol teilst du sie mit der ganzen Gruppe.</p>" +
            "<p>Innerhalb einer Quest lassen sich <b>Hinweise</b> und <b>Ziele</b> einzeln hinzufügen und unabhängig von der Quest selbst freigeben - so kannst du z.B. das erste Ziel sofort zeigen und ein späteres Ziel erst enthüllen, wenn die Gruppe so weit ist. Ein Häkchen an einem Ziel markiert es für die Gruppe als erledigt (durchgestrichen).</p>" +
            "<p><b>Für Spieler:</b> Das Quest-Logbuch taucht bei dir erst auf, sobald der Spielleiter mindestens eine Quest mit der Gruppe geteilt hat - vorher siehst du nichts davon. Du siehst nur Namen, Beschreibung sowie die Hinweise und Ziele, die freigegeben wurden.</p>" +
            "<p><i>Wie die Tischmitte bleibt dein Quest-Logbuch als Spielleiter in deinem Browser gespeichert, auch über einen Reload hinweg.</i></p>",

    spielerlog: "<h3>Mein Logbuch</h3>" +
                "<p>Dein eigenes Tagebuch, zusätzlich zum freien <b>Notizen</b>-Feld: pro Eintrag hältst du fest, welchen <b>NSC</b> du wann getroffen hast und was er dir erzählt bzw. welche Hinweise er gegeben hat. NSC und Zeitpunkt sind optional - manchmal reicht auch einfach nur der Text.</p>" +
                "<p>Die Einträge gehören ganz dir: sie bleiben in deinem Charakterbogen, gehen nie an den Spielleiter oder andere Spieler raus, und wandern beim <b>Speichern (JSON)</b> mit deinem Charakter mit.</p>",

    nscliste: "<h3>NSC-Liste</h3>" +
               "<p>Dein Gedächtnis für Nichtspielercharaktere, die im Laufe der Runde auftauchen - bleibt komplett bei dir, geht nie an Spieler raus.</p>" +
               "<p>Über <i>In NSC-Liste übernehmen</i> beim Zufallsgenerator landet ein gewürfelter NSC mit allen Feldern (Name, Ort, Rolle, Haltung, Auffälligkeit, Motivation, Wesen) direkt hier, ohne dass du etwas abtippen musst. Du kannst NSCs aber auch von Hand eintragen - dann reicht ein Name.</p>" +
               "<p>Das freie <b>Notiz</b>-Feld pro NSC ist der Platz, um festzuhalten, wie es mit ihm weiterging - wer ihn getroffen hat, ob er noch lebt, was er der Gruppe schuldet.</p>" +
               "<p>Über die Sortierung oben rechts lässt sich die Liste nach Ort, Name oder Haltung ordnen, statt nur nach Eintragsreihenfolge.</p>",

    talentbaum: "<h3>Talentbaum</h3>" +
                "<p>Der Talentbaum kommt aus dem aktiven Regelpaket. Du wählst deine <b>Hauptbäume</b> und dein <b>Wesen</b> - nur deren Skills werden angezeigt. Das Wesen bringt feste Vor- und Nachteile mit (die grünen und roten Kärtchen).</p>" +
                "<p><b>Skillpunkte (SP)</b> entstehen <i>getrennt je Baum</i>, aus dem Talentwert, der zu diesem Baum gehört (z.B. treibt dein Talent \"Nahkampf\" sowohl \"Nahkampf Klingen\" als auch \"Nahkampf Fäuste\"). Jede erreichte Schwelle (1, 10, 20 … 90, dann jeder Punkt bis 99) bringt einen SP - der zählt nur für Skills <i>dieses</i> Baums.</p>" +
                "<p><b>Rangpunkte (RP)</b> sind dagegen <i>ein gemeinsamer Topf</i> für alle Bäume: je Rangaufstieg in einem deiner drei Hauptbäume gibt es einen (max. 12). Ein RP bezahlt entweder das <i>erste Level</i> eines Skills (in jedem Baum, auch Wesen) oder eine <b>Besondere Eigenschaft</b> weiter unten.</p>" +
                "<p><b>Freischaltung:</b> Rang 1 ist immer offen. Für Rang 2+ in einem Baum brauchst du dort mindestens 2 SP auf Skills des Rangs darunter ausgegeben. Gesperrte Skills sind ausgegraut.</p>" +
                "<p><b>Kreuz-Leveln (⚡):</b> Hast du denselben Skill-Namen in zwei deiner Bäume gelernt, zählt sein <i>effektives Level</i> als Summe beider Käufe - das siehst du am Blitz-Symbol.</p>" +
                "<p><b>Besondere Eigenschaften</b> kosten je Pick 1 Rangpunkt. Ein Rang wird erst wählbar, wenn mindestens 2 deiner Bäume diesen Rang erreicht haben und du im Rang darunter schon 2 Eigenschaften gewählt hast.</p>" +
                "<p><b>Wesen/Monster:</b> Dessen Wert steigt nicht durch eigene Talentpunkte, sondern durch <b>Monsterpunkte</b>, die dir dein Spielleiter über seinen Eingriff-Knopf vergibt (z.B. nach einem überlebten Ritual oder einem bezwungenen Monster).</p>" +
                "<p><b>Im Kampf:</b> Unter <i>Gelernte Fähigkeiten</i> hakst du benutzte Skills ab und würfelst ihren Schaden direkt (🎲). <i>Alle auffrischen</i> setzt die Haken nach dem Kampf zurück.</p>" +
                "<p><i>Klick auf einen Skill/eine Eigenschaft = ein Level lernen, das kleine − gibt es zurück. Details siehst du, wenn du mit der Maus über der Kachel stehen bleibst.</i></p>" +
                "<p><i>Hinweis: Welcher Bogen-Talentwert genau zu welchem Hauptbaum gehört, ist eine Annahme, die die Runde mit dem Spielleiter noch bestätigen muss - kann sich also noch ändern.</i></p>",

    general: "<h3><i class='fa-solid fa-circle-info'></i> Willkommen bei HeroHQ</h3>" +
             "<p>Dieser interaktive Charakterbogen nimmt dir die Rechenarbeit am Pen&Paper-Tisch ab und bietet ein nahtloses Multiplayer-Erlebnis.</p>" +
             "<h4>Top Features:</h4>" +
             "<ul>" +
             "<li><b>1-Klick-Würfeln:</b> Klicke einfach auf deine Basis- oder Skill-Werte. Krits und Patzer (10%) werden automatisch erkannt!</li>" +
             "<li><b>Multiplayer (Live-Sync):</b> Der Spielleiter (GM) generiert einen Code, Spieler treten bei. Der GM sieht alle Würfe, Lebenspunkte und Inventar-Updates sofort auf seinem Bildschirm (GM Dashboard).</li>" +
             "<li><b>Integriertes Soundboard:</b> Der GM kann live Sounds & Ambient-Tracks für alle Spieler abspielen, mixen und faden.</li>" +
             "<li><b>Vibe-Themes:</b> Wähle dein Lieblings-Theme (Cyberpunk, Steampunk, Mafia...). Der GM kann als Host das Theme sogar für alle Spieler synchron erzwingen!</li>" +
             "<li><b>Drag & Drop Notizen:</b> Ziehe Einträge aus dem Logbuch oder deine gewürfelten Ergebnisse einfach mit der Maus rüber in dein Notizfeld.</li>" +
             "<li><b>Discord-Integration:</b> Verbinde einen Webhook, um alle Würfe direkt in euren Discord-Channel zu posten.</li>" +
             "</ul>" +
             "<p><i>Lokaler Speicher: Deine Eingaben werden live im Browser gespeichert. Dennoch solltest du vor/nach einer Session über 'Speichern (JSON)' ein Backup deiner Charakterdaten herunterladen!</i></p>"
};
